//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/car.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CarInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CarInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""car"",
    ""maps"": [
        {
            ""name"": ""car"",
            ""id"": ""3694f84c-8dca-4ca1-a5c7-96fa34c30fa0"",
            ""actions"": [
                {
                    ""name"": ""steeringWheel"",
                    ""type"": ""Value"",
                    ""id"": ""4d3e84e2-a4ad-4670-8f30-7440af183244"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""gas"",
                    ""type"": ""Value"",
                    ""id"": ""59f7fd44-9d8e-4a09-b928-119d17d9d5a1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""brake"",
                    ""type"": ""Value"",
                    ""id"": ""e67673b6-b10e-4db6-86a0-e4e5a268af88"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""clutch"",
                    ""type"": ""Value"",
                    ""id"": ""cc0998f8-87d3-4f7f-b3f4-4c98bdb2cf38"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GearR"",
                    ""type"": ""Button"",
                    ""id"": ""6587d4f4-38f4-409b-8f7b-432774d93e05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear1"",
                    ""type"": ""Button"",
                    ""id"": ""391ad9f6-2dc9-4264-bec9-76a5036ec732"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear2"",
                    ""type"": ""Button"",
                    ""id"": ""481018f7-2466-475b-92c9-41513a5faa54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear3"",
                    ""type"": ""Button"",
                    ""id"": ""a66a0863-8f7a-42ce-a926-c81b4554cc98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear4"",
                    ""type"": ""Button"",
                    ""id"": ""6812a230-a78a-4711-9d8b-46f15aa69fe5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear5"",
                    ""type"": ""Button"",
                    ""id"": ""cd7889f6-3032-400f-bb6e-026531923e43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""61b6a31f-0a93-4c5b-a396-904da58b1f8e"",
                    ""path"": ""<HID::44F B67F>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""gas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e04d6a68-af82-4ef2-819f-c5bae4a39829"",
                    ""path"": ""<HID::44F B67F>/stick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""steeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88ac1f1d-7353-4ef7-847a-b7e735c376e4"",
                    ""path"": ""<HID::44F B67F>/stick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f68fe03f-aa93-438f-87b8-2298e122b016"",
                    ""path"": ""<HID::44F B67F>/slider"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""clutch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0e6ff60-1b06-4564-be1c-3c0662510547"",
                    ""path"": ""<HID::Thustmaster T500 RS Gear Shift>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""365a0f44-d086-4afe-8359-c97af3b8ea94"",
                    ""path"": ""<HID::Thustmaster T500 RS Gear Shift>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e9383de-fd24-4e94-8c12-88da00ded151"",
                    ""path"": ""<HID::Thustmaster T500 RS Gear Shift>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df0fbb38-009c-482a-aad9-5102ab6c4f79"",
                    ""path"": ""<HID::Thustmaster T500 RS Gear Shift>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21a10b49-6ee7-4c40-93e2-d99e80e43564"",
                    ""path"": ""<HID::Thustmaster T500 RS Gear Shift>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9aeddf6f-5283-4746-9a91-06e2ce805a4a"",
                    ""path"": ""<HID::Thustmaster T500 RS Gear Shift>/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // car
        m_car = asset.FindActionMap("car", throwIfNotFound: true);
        m_car_steeringWheel = m_car.FindAction("steeringWheel", throwIfNotFound: true);
        m_car_gas = m_car.FindAction("gas", throwIfNotFound: true);
        m_car_brake = m_car.FindAction("brake", throwIfNotFound: true);
        m_car_clutch = m_car.FindAction("clutch", throwIfNotFound: true);
        m_car_GearR = m_car.FindAction("GearR", throwIfNotFound: true);
        m_car_Gear1 = m_car.FindAction("Gear1", throwIfNotFound: true);
        m_car_Gear2 = m_car.FindAction("Gear2", throwIfNotFound: true);
        m_car_Gear3 = m_car.FindAction("Gear3", throwIfNotFound: true);
        m_car_Gear4 = m_car.FindAction("Gear4", throwIfNotFound: true);
        m_car_Gear5 = m_car.FindAction("Gear5", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // car
    private readonly InputActionMap m_car;
    private List<ICarActions> m_CarActionsCallbackInterfaces = new List<ICarActions>();
    private readonly InputAction m_car_steeringWheel;
    private readonly InputAction m_car_gas;
    private readonly InputAction m_car_brake;
    private readonly InputAction m_car_clutch;
    private readonly InputAction m_car_GearR;
    private readonly InputAction m_car_Gear1;
    private readonly InputAction m_car_Gear2;
    private readonly InputAction m_car_Gear3;
    private readonly InputAction m_car_Gear4;
    private readonly InputAction m_car_Gear5;
    public struct CarActions
    {
        private @CarInputs m_Wrapper;
        public CarActions(@CarInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @steeringWheel => m_Wrapper.m_car_steeringWheel;
        public InputAction @gas => m_Wrapper.m_car_gas;
        public InputAction @brake => m_Wrapper.m_car_brake;
        public InputAction @clutch => m_Wrapper.m_car_clutch;
        public InputAction @GearR => m_Wrapper.m_car_GearR;
        public InputAction @Gear1 => m_Wrapper.m_car_Gear1;
        public InputAction @Gear2 => m_Wrapper.m_car_Gear2;
        public InputAction @Gear3 => m_Wrapper.m_car_Gear3;
        public InputAction @Gear4 => m_Wrapper.m_car_Gear4;
        public InputAction @Gear5 => m_Wrapper.m_car_Gear5;
        public InputActionMap Get() { return m_Wrapper.m_car; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CarActions set) { return set.Get(); }
        public void AddCallbacks(ICarActions instance)
        {
            if (instance == null || m_Wrapper.m_CarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarActionsCallbackInterfaces.Add(instance);
            @steeringWheel.started += instance.OnSteeringWheel;
            @steeringWheel.performed += instance.OnSteeringWheel;
            @steeringWheel.canceled += instance.OnSteeringWheel;
            @gas.started += instance.OnGas;
            @gas.performed += instance.OnGas;
            @gas.canceled += instance.OnGas;
            @brake.started += instance.OnBrake;
            @brake.performed += instance.OnBrake;
            @brake.canceled += instance.OnBrake;
            @clutch.started += instance.OnClutch;
            @clutch.performed += instance.OnClutch;
            @clutch.canceled += instance.OnClutch;
            @GearR.started += instance.OnGearR;
            @GearR.performed += instance.OnGearR;
            @GearR.canceled += instance.OnGearR;
            @Gear1.started += instance.OnGear1;
            @Gear1.performed += instance.OnGear1;
            @Gear1.canceled += instance.OnGear1;
            @Gear2.started += instance.OnGear2;
            @Gear2.performed += instance.OnGear2;
            @Gear2.canceled += instance.OnGear2;
            @Gear3.started += instance.OnGear3;
            @Gear3.performed += instance.OnGear3;
            @Gear3.canceled += instance.OnGear3;
            @Gear4.started += instance.OnGear4;
            @Gear4.performed += instance.OnGear4;
            @Gear4.canceled += instance.OnGear4;
            @Gear5.started += instance.OnGear5;
            @Gear5.performed += instance.OnGear5;
            @Gear5.canceled += instance.OnGear5;
        }

        private void UnregisterCallbacks(ICarActions instance)
        {
            @steeringWheel.started -= instance.OnSteeringWheel;
            @steeringWheel.performed -= instance.OnSteeringWheel;
            @steeringWheel.canceled -= instance.OnSteeringWheel;
            @gas.started -= instance.OnGas;
            @gas.performed -= instance.OnGas;
            @gas.canceled -= instance.OnGas;
            @brake.started -= instance.OnBrake;
            @brake.performed -= instance.OnBrake;
            @brake.canceled -= instance.OnBrake;
            @clutch.started -= instance.OnClutch;
            @clutch.performed -= instance.OnClutch;
            @clutch.canceled -= instance.OnClutch;
            @GearR.started -= instance.OnGearR;
            @GearR.performed -= instance.OnGearR;
            @GearR.canceled -= instance.OnGearR;
            @Gear1.started -= instance.OnGear1;
            @Gear1.performed -= instance.OnGear1;
            @Gear1.canceled -= instance.OnGear1;
            @Gear2.started -= instance.OnGear2;
            @Gear2.performed -= instance.OnGear2;
            @Gear2.canceled -= instance.OnGear2;
            @Gear3.started -= instance.OnGear3;
            @Gear3.performed -= instance.OnGear3;
            @Gear3.canceled -= instance.OnGear3;
            @Gear4.started -= instance.OnGear4;
            @Gear4.performed -= instance.OnGear4;
            @Gear4.canceled -= instance.OnGear4;
            @Gear5.started -= instance.OnGear5;
            @Gear5.performed -= instance.OnGear5;
            @Gear5.canceled -= instance.OnGear5;
        }

        public void RemoveCallbacks(ICarActions instance)
        {
            if (m_Wrapper.m_CarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICarActions instance)
        {
            foreach (var item in m_Wrapper.m_CarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CarActions @car => new CarActions(this);
    public interface ICarActions
    {
        void OnSteeringWheel(InputAction.CallbackContext context);
        void OnGas(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnClutch(InputAction.CallbackContext context);
        void OnGearR(InputAction.CallbackContext context);
        void OnGear1(InputAction.CallbackContext context);
        void OnGear2(InputAction.CallbackContext context);
        void OnGear3(InputAction.CallbackContext context);
        void OnGear4(InputAction.CallbackContext context);
        void OnGear5(InputAction.CallbackContext context);
    }
}
